"""add transaction_id in reviews table

Revision ID: 01ac41f9543a
Revises: 03f99501e1e0
Create Date: 2024-12-13 16:52:51.402386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ac41f9543a'
down_revision = '03f99501e1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_address_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'transactions_history', ['transactions_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transactions_id')

    with op.batch_alter_table('users_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_address_user_id'))

    op.drop_table('users_address')
    # ### end Alembic commands ###
