"""add column is_active in seller_profile table

Revision ID: 0a497e9475bb
Revises: 01ac41f9543a
Create Date: 2024-12-13 22:51:31.294837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a497e9475bb'
down_revision = '01ac41f9543a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_constraint('user_interests_id_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('user_interests_id_key', ['id'])

    with op.batch_alter_table('seller_profile', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
