"""add is_seller column constraint nullable=False

Revision ID: 3004c64dcf28
Revises: 7140d403abd3
Create Date: 2024-12-16 17:39:29.397780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3004c64dcf28'
down_revision = '7140d403abd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_seller',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_seller',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
