"""add is_out_stock column in producst table

Revision ID: 3321bc33214b
Revises: 3004c64dcf28
Create Date: 2024-12-16 20:47:52.445272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3321bc33214b'
down_revision = '3004c64dcf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_out_of_stock', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_out_of_stock')

    # ### end Alembic commands ###
