"""add invoice_number to orders column

Revision ID: 3663af35fe6e
Revises: 699708f2d06b
Create Date: 2024-12-10 22:33:16.956849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3663af35fe6e'
down_revision = '699708f2d06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
