"""fix is_deleted column in reviews table

Revision ID: 37c33a6e8901
Revises: 8c160475b458
Create Date: 2024-12-09 21:01:21.172035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c33a6e8901'
down_revision = '8c160475b458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_delted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
