"""add id in user_interests table

Revision ID: 4d0402cdd355
Revises: a5b02a72b283
Create Date: 2024-12-09 01:53:02.732588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0402cdd355'
down_revision = 'a5b02a72b283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
