"""add unique constrain in users_interest table

Revision ID: 7146e848e0cc
Revises: 4d0402cdd355
Create Date: 2024-12-09 03:05:51.721654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7146e848e0cc'
down_revision = '4d0402cdd355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_category', ['user_id', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_category', type_='unique')

    # ### end Alembic commands ###
