"""add voucher and wishlist tables

Revision ID: a5b02a72b283
Revises: 3eeaaf1d7e0c
Create Date: 2024-12-09 00:08:23.174897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b02a72b283'
down_revision = '3eeaaf1d7e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('user_interests', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uix_user_category', ['user_id', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_category', type_='unique')

    op.drop_table('wishlist')
    # ### end Alembic commands ###
